version: "3.7"
services:
  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - "./database:/var/lib/mysql"
    networks:
      suwanasilver_net:
        ipv4_address: ${PROJECT_IP}.2
    user: '1000'
  app:
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-app
    build:
      args:
        user: ${PROJECT_USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/webroot
    volumes:
      - ./:/var/www
      - ./home:/home/${PROJECT_USER}
    depends_on:
    - db
    networks:
      suwanasilver_net:
        ipv4_address: ${PROJECT_IP}.3
  nginx:
    image: nginx:1.17-alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      suwanasilver_net:
        ipv4_address: ${PROJECT_IP}.4
  redis:
    image: redis:latest
    container_name: ${PROJECT_NAME}-redis
    networks:
      suwanasilver_net:
        ipv4_address: ${PROJECT_IP}.5

networks:
  suwanasilver_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${PROJECT_IP}.0/24

volumes:
  db:
    driver: local